### PR TITLE
Added material design

### PR DESCRIPTION
**Pull request by freundTech**

### CODE REVIEW

**Comment by pkern** [comment]
Two comments (and thanks for your continued efforts!):

* The top bar renders black text for me. Is this intentional? I feel like the color scheme is supposed to be white there.
* There is a back navigation button at the top. I suppose I know why, but I wonder if it really makes sense. The outer activity is only useful if there's no value to display and once there is one, in theory it could go away. So the question is if the top bar can be rendered without the back button. (Apart from the fact that I'd really have liked capturing point in time values per wallet, at which point a hamburger menu would make sense, I guess.)

**Comment by freundTech** [comment]
1. The black text is just the default setting when using a light theme (Theme.AppCompat.Light), while white text is the default when using a dark theme (Theme.AppCompat). Changing it without changing the whole theme should be possible, but I'll have to look into that.
2. I just enabled the back button, because the app bar looked empty and pointless without any buttons. I think it looks better with it, but it can of course also be replace with something else.

**Comment by pkern** [comment]
Would it be possible to make the text white? =)

**Comment by pkern** [comment]
Closing this as the project is obsolete due to the new KITCard system not publishing any specs and the app hence having been depublished.

**Pull request closed without merging**
